# use this for e2e tests

services:
  postgres:
    image: postgres:18
    env_file:
      - .env
    ports:
      - "5432:5432"

  backend:
    image: paulwoods/equipment-backend:latest
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  frontend:
    image: paulwoods/equipment-frontend:latest
    env_file:
      - .env
    ports:
      - "5173:5173"
    depends_on:
      - backend

#  caddy:
#    image: caddy:2-alpine
#    ports:
#      - "80:80"
#      - "443:443"
#    env_file:
#      - .env
#    volumes:
#      - ./Caddyfile:/etc/caddy/Caddyfile:ro
#      - ./caddy_data:/data
#      - ./caddy_config:/config
#    depends_on:
#      - frontend
#      - backend
#    restart: unless-stopped
#    logging:
#      driver: json-file
#      options:
#        max-size: "10m"
#        max-file: "3"
